In [1]:
import pandas as pd

df = pd.read_csv('../data/auto.csv', index_col='ID')
df

        CarNumber    Make_n_model  Refund    Fines  History
ID
0    Y163O8161RUS      Ford Focus     2.0   3200.0      NaN
1     E432XX77RUS    Toyota Camry     1.0   6500.0      NaN
2     7184TT36RUS      Ford Focus     1.0   2100.0      NaN
3    X582HE161RUS      Ford Focus     2.0   2000.0      NaN
4    E34877152RUS      Ford Focus     2.0   6100.0      NaN
..            ...             ...     ...      ...      ...
926  Y163O8161RUS      Ford Focus     2.0   1600.0      NaN
927  M0309X197RUS      Ford Focus     1.0  22300.0      NaN
928  O673E8197RUS      Ford Focus     2.0    600.0      NaN
929  8610T8154RUS      Ford Focus     1.0   2000.0      NaN
930  H419XE197RUS  Toyota Corolla     2.0      NaN      2.0

[931 rows x 5 columns]

In [2]:
initial_count = df.count()
print(f"Исходное количество:\n{initial_count}")

Исходное количество:
CarNumber       931
Make_n_model    931
Refund          914
Fines           869
History          82
dtype: int64

In [3]:
df = df.drop_duplicates(subset=['CarNumber', 'Make_n_model', 'Fines'], keep='last')
print("Количество записей после удаления:", len(df))
df

Количество записей после удаления: 725

        CarNumber    Make_n_model  Refund    Fines  History
ID
0    Y163O8161RUS      Ford Focus     2.0   3200.0      NaN
1     E432XX77RUS    Toyota Camry     1.0   6500.0      NaN
2     7184TT36RUS      Ford Focus     1.0   2100.0      NaN
3    X582HE161RUS      Ford Focus     2.0   2000.0      NaN
5    92918M178RUS      Ford Focus     1.0   5700.0      NaN
..            ...             ...     ...      ...      ...
926  Y163O8161RUS      Ford Focus     2.0   1600.0      NaN
927  M0309X197RUS      Ford Focus     1.0  22300.0      NaN
928  O673E8197RUS      Ford Focus     2.0    600.0      NaN
929  8610T8154RUS      Ford Focus     1.0   2000.0      NaN
930  H419XE197RUS  Toyota Corolla     2.0      NaN      2.0

[725 rows x 5 columns]

In [9]:
#NAN
print("До обработки:")
print(df.isnull().sum())
#----
df = df.dropna(thresh=len(df)-500, axis=1)
df
#----
df.loc[:, 'Refund'] = df['Refund'].ffill()
df.loc[:, 'Fines'] = df['Fines'].fillna(df['Fines'].mean())
df

До обработки:
CarNumber    0
Refund       0
Fines        0
Make         0
Model        9
dtype: int64

        CarNumber  Refund         Fines    Make    Model
ID
0    Y163O8161RUS     2.0   3200.000000    Ford    Focus
1     E432XX77RUS     1.0   6500.000000  Toyota    Camry
2     7184TT36RUS     1.0   2100.000000    Ford    Focus
3    X582HE161RUS     2.0   2000.000000    Ford    Focus
5    92918M178RUS     1.0   5700.000000    Ford    Focus
..            ...     ...           ...     ...      ...
926  Y163O8161RUS     2.0   1600.000000    Ford    Focus
927  M0309X197RUS     1.0  22300.000000    Ford    Focus
928  O673E8197RUS     2.0    600.000000    Ford    Focus
929  8610T8154RUS     1.0   2000.000000    Ford    Focus
930  H419XE197RUS     2.0   8594.586466  Toyota  Corolla

[725 rows x 5 columns]

In [5]:
print("Пропуски после обработки:")
print(df.isnull().sum())

Пропуски после обработки:
CarNumber       0
Make_n_model    0
Refund          0
Fines           0
dtype: int64

In [6]:
df[['Make', 'Model']] = df['Make_n_model'].apply(
    lambda x: pd.Series(x.split(' ', 1)) if pd.notnull(x) else pd.Series([None, None])
)
df = df.drop('Make_n_model', axis=1)  # Удаляем исходный столбец

In [7]:
df.to_json('../data/auto.json', orient='records')